spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ecommerce
server:
  port: 8080
jwt:
  secret: spring-app-ecommerce
  # 30 = min -> 180 seconds -> 180.000 milliseconds
  expiration: 1800000
