spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ecommerce
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000
  cache:
    type: redis
server:
  port: 8080
jwt:
  secret: spring-app-ecommerce
  # 30 = min -> 180 seconds -> 1.800.000 milliseconds
  expiration: 1800000
